if: branch !~ ^v\d
dist: xenial
addons:
  apt:
    packages: libfaketime
language: node_js
node_js: node
cache: npm
before_install: curl -sSL https://nodejs.org/download/release/v12.0.0/node-v12.0.0-linux-x64.tar.gz | tar zxf - node-v12.0.0-linux-x64/bin/node
