if: branch !~ ^v\d
dist: xenial
addons:
  apt:
    packages: libfaketime
language: node_js
node_js: node
cache: npm
before_script: npm install --no-package-lock --no-save full-icu
after_success: node_modules/.bin/nyc report > coverage.lcov && bash <(curl -s https://codecov.io/bash) -X gcov
